version: "3.8"
services:
  frontend:
    build:
      context: .
      target: develop-stage
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    volumes:
      - ".:/app"
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    #command: [nginx-debug, "-g", "daemon off;"]
    command: ["npm", "run", "serve"]
