version: "3.8"
services:
  app:
    build: .
    container_name: webservice_vet
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - db_vet
    command: ["npm", "run", dev]
